// DO NOT EDIT. This file is generated by `fresh`.
// This file SHOULD be checked into source version control.
// To update this file, run `fresh manifest`.

import * as $0 from "./routes/index.tsx";
import * as $1 from "./routes/launches.tsx";
import * as $2 from "./routes/streams.tsx";
import * as $$0 from "./islands/Header.tsx";

const manifest = {
  routes: {
    "./routes/index.tsx": $0,
    "./routes/launches.tsx": $1,
    "./routes/streams.tsx": $2,
  },
  islands: {
    "./islands/Header.tsx": $$0,
  },
  baseUrl: import.meta.url,
};

export default manifest;
