name: Lighthouse CI
on: push
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v9
        with:
          urls: |
            https://ltx.deno.dev
            https://ltx.deno.dev/launches
            https://ltx.deno.dev/streams
            https://ltx.deno.dev/about
            https://ltx.deno.dev/wiki
          uploadArtifacts: true # save results as an action artifacts
          temporaryPublicStorage: true # upload lighthouse report to the temporary storage
