name: Lighthouse
on: push

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Lighthouse
      uses: foo-software/lighthouse-check-action@master
      with:
        urls: 'https://ltx.deno.dev,https://ltx.deno.dev/launches,https://ltx.deno.dev/streams,https://ltx.deno.dev/about,https://ltx.deno.dev/wiki,https://ltx.deno.dev/wiki/template'
